name: Build Windows App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pymsgbox pywin32
        
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed --name TUGoToWork auto_attendance.py
        
    - name: Create release package
      run: |
        mkdir release
        copy dist\TUGoToWork.exe release\
        copy README.md release\
        powershell Compress-Archive -Path release\* -DestinationPath TUGoToWork-windows.zip
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: TUGoToWork-windows
        path: TUGoToWork-windows.zip
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: TUGoToWork-windows.zip
        body: |
          ## TU Go To Work Windows App
          
          ### 설치 방법
          1. ZIP 파일을 다운로드하고 압축 해제
          2. `TUGoToWork.exe` 실행
          3. "시작프로그램에 등록" 선택
          
          ### 시스템 요구사항
          - Windows 10/11
          
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
