name: Build Windows EXE and Release

on:
  push:
    tags:
      - 'v*'   # v로 시작하는 태그를 push할 때만 동작

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Nuitka and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka pywin32

      - name: Compile with Nuitka
        run: python -m nuitka --onefile --windows-console-mode=disable --enable-plugin=tk-inter --assume-yes-for-downloads --output-dir=dist --output-filename=TUGoToWork auto_attendance.py

      - name: Create Release with Nuitka EXE
        uses: softprops/action-gh-release@v1
        with:
          files: dist/TUGoToWork.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}