name: Build Windows EXE and Release

on:
  push:
    tags:
      - 'v*'   # v로 시작하는 태그를 push할 때만 동작

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pywin32

      - name: Build with PyInstaller (Folder)
        run: pyinstaller --onedir --windowed --name TUGoToWork auto_attendance.py

      - name: Zip the output folder
        run: Compress-Archive -Path dist/TUGoToWork -DestinationPath dist/TUGoToWork.zip

      - name: Create Release with Zip
        uses: softprops/action-gh-release@v1
        with:
          files: dist/TUGoToWork.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}